
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LARGURA = 10;
  public static final int SEMICOLON = 20;
  public static final int RPAREN = 17;
  public static final int RBRACE = 15;
  public static final int RETANGULO = 3;
  public static final int COR = 7;
  public static final int ALTURA = 11;
  public static final int RAIO = 9;
  public static final int COLON = 19;
  public static final int LPAREN = 16;
  public static final int LBRACE = 14;
  public static final int ID = 23;
  public static final int POSICAO = 8;
  public static final int STRING = 22;
  public static final int COMMA = 18;
  public static final int NUMBER = 21;
  public static final int EOF = 0;
  public static final int BASE = 13;
  public static final int ELIPSE = 6;
  public static final int error = 1;
  public static final int LADO = 12;
  public static final int CIRCULO = 2;
  public static final int TRIANGULO = 4;
  public static final int QUADRADO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CIRCULO",
  "RETANGULO",
  "TRIANGULO",
  "QUADRADO",
  "ELIPSE",
  "COR",
  "POSICAO",
  "RAIO",
  "LARGURA",
  "ALTURA",
  "LADO",
  "BASE",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "COMMA",
  "COLON",
  "SEMICOLON",
  "NUMBER",
  "STRING",
  "ID"
  };
}

