
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RBRACE = 7;
  public static final int WIDTH = 10;
  public static final int CIRCLE = 4;
  public static final int COLOR = 13;
  public static final int COLON = 8;
  public static final int LBRACE = 6;
  public static final int ID = 15;
  public static final int COMMA = 9;
  public static final int COLORVAL = 16;
  public static final int NUMBER = 17;
  public static final int EOF = 0;
  public static final int POSITION = 14;
  public static final int HEIGHT = 11;
  public static final int SHAPE = 2;
  public static final int RECTANGLE = 3;
  public static final int RADIUS = 12;
  public static final int error = 1;
  public static final int TRIANGLE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SHAPE",
  "RECTANGLE",
  "CIRCLE",
  "TRIANGLE",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "WIDTH",
  "HEIGHT",
  "RADIUS",
  "COLOR",
  "POSITION",
  "ID",
  "COLORVAL",
  "NUMBER"
  };
}

