
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 13;
  public static final int RCOL = 4;
  public static final int PV = 7;
  public static final int EOF = 0;
  public static final int ID = 12;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int INC = 10;
  public static final int LT = 9;
  public static final int LPAREN = 5;
  public static final int DO = 2;
  public static final int OUT = 11;
  public static final int LCOL = 3;
  public static final int ATRIB = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DO",
  "LCOL",
  "RCOL",
  "LPAREN",
  "RPAREN",
  "PV",
  "ATRIB",
  "LT",
  "INC",
  "OUT",
  "ID",
  "NUM"
  };
}

