
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 7;
  public static final int MOVE = 2;
  public static final int LEFT = 3;
  public static final int NUMBER = 9;
  public static final int LOOP = 5;
  public static final int EOF = 0;
  public static final int RIGHT = 4;
  public static final int error = 1;
  public static final int TIMES = 6;
  public static final int RBRACE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MOVE",
  "LEFT",
  "RIGHT",
  "LOOP",
  "TIMES",
  "LBRACE",
  "RBRACE",
  "NUMBER"
  };
}

