
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATTR_VALUE = 7;
  public static final int TAG_OPEN = 2;
  public static final int EOF = 0;
  public static final int EQ = 5;
  public static final int TAG_END_OPEN = 3;
  public static final int error = 1;
  public static final int TEXT = 8;
  public static final int TAG_CLOSE = 4;
  public static final int NAME = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TAG_OPEN",
  "TAG_END_OPEN",
  "TAG_CLOSE",
  "EQ",
  "NAME",
  "ATTR_VALUE",
  "TEXT"
  };
}

