
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CTL_OPEN = 4;
  public static final int IDENT = 9;
  public static final int EOF = 0;
  public static final int IF = 6;
  public static final int ELSE = 7;
  public static final int error = 1;
  public static final int VAR_CLOSE = 3;
  public static final int TEXT = 10;
  public static final int CTL_CLOSE = 5;
  public static final int ENDIF = 8;
  public static final int VAR_OPEN = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR_OPEN",
  "VAR_CLOSE",
  "CTL_OPEN",
  "CTL_CLOSE",
  "IF",
  "ELSE",
  "ENDIF",
  "IDENT",
  "TEXT"
  };
}

