
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 16;
  public static final int READ = 12;
  public static final int LT = 21;
  public static final int ELSE = 9;
  public static final int PLUS = 14;
  public static final int RBRACE = 28;
  public static final int RPAREN = 26;
  public static final int INT = 5;
  public static final int THEN = 8;
  public static final int SEMI = 29;
  public static final int WHILE = 10;
  public static final int END = 4;
  public static final int IF = 7;
  public static final int LBRACE = 27;
  public static final int LPAREN = 25;
  public static final int GT = 22;
  public static final int ID = 31;
  public static final int LE = 23;
  public static final int WRITE = 13;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int DO = 11;
  public static final int COMMA = 30;
  public static final int FLOAT = 6;
  public static final int NUMBER = 32;
  public static final int EOF = 0;
  public static final int DIVIDE = 17;
  public static final int GE = 24;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int ASSIGN = 18;
  public static final int NEQ = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "INT",
  "FLOAT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "READ",
  "WRITE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "ASSIGN",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LE",
  "GE",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COMMA",
  "ID",
  "NUMBER"
  };
}

