
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 5;
  public static final int WHERE = 4;
  public static final int GTEQ = 10;
  public static final int NUMBER = 16;
  public static final int NOTEQ = 12;
  public static final int ALL = 13;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int EQ = 7;
  public static final int ID = 14;
  public static final int GT = 8;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int SELECT = 3;
  public static final int FROM = 2;
  public static final int LTEQ = 11;
  public static final int LT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FROM",
  "SELECT",
  "WHERE",
  "AND",
  "COMMA",
  "EQ",
  "GT",
  "LT",
  "GTEQ",
  "LTEQ",
  "NOTEQ",
  "ALL",
  "ID",
  "STRING",
  "NUMBER"
  };
}

