
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 12;
  public static final int PV = 6;
  public static final int EQ = 8;
  public static final int EOF = 0;
  public static final int IF = 2;
  public static final int ID = 11;
  public static final int GT = 10;
  public static final int ELSE = 3;
  public static final int error = 1;
  public static final int RPAREN = 5;
  public static final int LT = 9;
  public static final int LPAREN = 4;
  public static final int ATRIB = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "LPAREN",
  "RPAREN",
  "PV",
  "ATRIB",
  "EQ",
  "LT",
  "GT",
  "ID",
  "NUM"
  };
}

