
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 9;
  public static final int COLON = 12;
  public static final int SYMBOL = 16;
  public static final int INITIAL = 5;
  public static final int TRANSITIONS = 7;
  public static final int EOF = 0;
  public static final int AUTOMATON = 2;
  public static final int ARROW = 13;
  public static final int ALPHABET = 4;
  public static final int COMMA = 11;
  public static final int error = 1;
  public static final int SEMICOLON = 14;
  public static final int IDENTIFIER = 15;
  public static final int RBRACE = 10;
  public static final int END = 8;
  public static final int FINAL = 6;
  public static final int STATES = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AUTOMATON",
  "STATES",
  "ALPHABET",
  "INITIAL",
  "FINAL",
  "TRANSITIONS",
  "END",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "COLON",
  "ARROW",
  "SEMICOLON",
  "IDENTIFIER",
  "SYMBOL"
  };
}

